# Generated by Django 3.2.7 on 2021-12-05 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_interface', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='log_data',
            field=models.BinaryField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='simulation',
            name='output_data',
            field=models.FileField(default=None, upload_to='simulations/<django.db.models.fields.AutoField>'),
        ),
        migrations.AddField(
            model_name='simulation',
            name='user_email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
